name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Library
      run: cargo build --manifest-path /home/runner/work/Shared-Object-Library-Using-Rust/Shared-Object-Library-Using-Rust/SharedObjectFile/addition_library/Cargo.toml --verbose
    - name: Build Client
      run: cargo build --manifest-path /home/runner/work/Shared-Object-Library-Using-Rust/Shared-Object-Library-Using-Rust/SharedObjectFile/addition_client/Cargo.toml --verbose
    - name: Run Client
      run: cargo run --manifest-path /home/runner/work/Shared-Object-Library-Using-Rust/Shared-Object-Library-Using-Rust/SharedObjectFile/addition_client/Cargo.toml --verbose
